image: alpine/3.19
secrets:
- 821cf89d-a5e2-45e0-8431-1cf5de13c32d
- 69657a19-c936-4d94-89e4-131206a5893c
- cbe41c27-8296-4f78-969d-0f65de96c898
packages:
- ruby
- ruby-dev
- libffi-dev
- nodejs
- rsync
environment:
  site: gosha.net
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    cd $site
    sudo bundle install
    /bin/sh ./updategitinfo.sh
    sudo bundle exec jekyll build
- deploy: |
    cd $site/build
    rsync -rvlh --delete . bubundel:/var/www/gosha.net
