image: alpine/edge
secrets:
- 821cf89d-a5e2-45e0-8431-1cf5de13c32d
- cbe41c27-8296-4f78-969d-0f65de96c898
- 75f1453a-7f9a-40ad-b0f8-d5d695bd7779
packages:
- ruby
- ruby-dev
- libffi-dev
- nodejs
- rsync
environment:
  site: gosha.net
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    cd $site
    sudo bundle install
    /bin/sh ./updategitinfo.sh
    sudo bundle exec jekyll build
- deploy: |
    cd $site/build
    rsync -Pvrthl --delete --info=progress2 . bubundel:/var/www/gosha.net
