# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gosha Tcherednitchenko
author: Gosha Tcherednitchenko
email: mail@gosha.net
description: >- # this means to ignore newlines until "baseurl:"
  Photography, design, writing, and software projects by Gosha Tcherednitchenko
baseurl: "" # the subpath of your site, e.g. /blog
url: https://gosha.net # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty
timezone: Europe/London
meta:
  theme_color: "#000"
  twitter_card_type: "summary"
  twitter: "goshatch"
  mastodon: "@gosha@merveilles.town"
  github_username: "goshatch"
  default_social_image: "/assets/images/default_social.png"

mastodon:
  username: gosha
  instance: merveilles.town

# Build settings
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-figure
  - jekyll/mastodon_webfinger

exclude:
  - updategitinfo.sh
  - README.md

destination: build

jekyll-figure:
  paragraphs: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /:year/:slug/

autoprefixer:
  browsers:
    - last 2 versions

collections:
  projects:
    rss_feed: true
    output: true
  books_read:
    rss_feed: true

feed:
  collections:
    projects:
      path: "/projects/feed.xml"
