#+TITLE: Source code for gueorgui.net
#+OPTIONS: toc:nil

This repository contains the source code and assets for my personal homepage,
[[https://gueorgui.net][gueorgui.net]].

Please feel free to look around and get inspiration. If something is unclear,
please [[https://github.com/gueorgui/gueorgui.github.io/issues][open an issue]] or [[mailto:hello@gueorgui.net?subject=Question about your website][email me]].

** Running a local copy

In order to run the website localy, clone the repository and use the =source=
branch:

#+BEGIN_SRC bash
$ bundle install
$ bundle exec jekyll serve -l
#+END_SRC

** Deployment

The =source= branch contains the source code, and the =master= branch contains
the result of the build, which is available via github pages.

The configuration files for building and deploying the site to Github Pages are
located i[[https://github.com/gueorgui/gueorgui.github.io/tree/source/.github][in the =.github= directory]] of the =source= branch.

** Licensing and copyright

Please note that all the content in this repository is copyrighted, most of the
time by me, and when specified, by others. You are free to re-use source code,
but please do not copy or re-use images or other assets without permission.
